{:id "1234567",
 :assetId "123456",
 :location {:site "AMS-01",
            :suite "HALL1-23",
            :rack "12",
            :unit "12"},

 :networkInterfaces {:public {:mac "42:42:42:42:C2:FC",
                              :ip "42.0.0.10/26",
                              :gateway "42.0.0.42",
                              :ports [{:name "EVO-5.7.32-1", :port "0-31"}]},
                              :internal {:mac "42:42:42:42:C2:FD",
                                         :ip nil,
                                         :gateway nil,
                                         :ports [{:name "AMS-01-5.7-32-INT-SW01", :port "0-31"}]},
                                         :remoteManagement {:mac "42:42:42:42:42:CD",
                                                            :ip "10.0.0.10/26",
                                                            :gateway "10.0.0.42",
                                                            :ports []}},
                                                            
  :featureAvailability {:automation true,
                        :powerCycle true,
                        :ipmiReboot false,
                        :privateNetwork true,
                        :remoteManagement true},

  :contract {:id "132456",
             :customerId "1610125700",
             :salesOrgId "2000",
             :deliveryStatus "ACTIVE",
             :reference "lsw-123456",
             :internalReference "MYID002"}}
